#!/bin/bash

# Verificamos si el número de argumentos es correcto
if [ "$#" -ne 11 ]; then
    echo "Error: se requieren 12 parámetros"
    echo "Uso: $0 <NUM_TOTAL_NODOS> <NUM_CONSULTAS> <NUM_RESERVAS> <NUM_PAGOS> <NUM_ADMINISTRACIONES> <NUM_ANULACIONES> <TIEMPO_SC_CONSULTAS> <TIEMPO_SC_RESERVAS> <TIEMPO_SC_PAGOS> <TIEMPO_SC_ADMINISTRACIONES> <TIEMPO_SC_ANULACIONES>"
    exit 1
fi

# Asignamos los parámetros a variables
NUM_TOTAL_NODOS=$1
NUM_CONSULTAS=$2
NUM_RESERVAS=$3
NUM_PAGOS=$4
NUM_ADMINISTRACIONES=$5
NUM_ANULACIONES=$6
TIEMPO_SC_CONSULTAS=$7
TIEMPO_SC_RESERVAS=$8
TIEMPO_SC_PAGOS=$9
TIEMPO_SC_ADMINISTRACIONES=${10}
TIEMPO_SC_ANULACIONES=${11}

# Parar procesos anteriores
pkill -f './nodo'
ipcrm --all=msg

# Lanzamos los programas con ID de nodo incremental
for (( ID_NODO=1; ID_NODO<=NUM_TOTAL_NODOS; ID_NODO++ ))
do
    echo "Lanzando nodo $ID_NODO..."
    ./nodo $NUM_TOTAL_NODOS $ID_NODO $NUM_CONSULTAS $NUM_RESERVAS $NUM_PAGOS $NUM_ADMINISTRACIONES $NUM_ANULACIONES \
    $TIEMPO_SC_CONSULTAS $TIEMPO_SC_RESERVAS $TIEMPO_SC_PAGOS $TIEMPO_SC_ADMINISTRACIONES $TIEMPO_SC_ANULACIONES &
done
